name: minervalab_docs
channels:
  - conda-forge
dependencies:
- appmode
- bqplot=0.11.6
- scipy
- numpy
- pip
- matplotlib
- qgrid
- ipywidgets
- pandas
- jupyter_sphinx
- sphinx==3.4.3
- pip:
  - ipyvolume
  - jupyter_latex_envs
